// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkEUhURDJzrBwUkAa41GXy928XXXiY23A',
    appId: '1:1092996801737:web:ee7c1686c363c83764d918',
    messagingSenderId: '1092996801737',
    projectId: 'jahotel-c3b37',
    authDomain: 'jahotel-c3b37.firebaseapp.com',
    storageBucket: 'jahotel-c3b37.appspot.com',
    measurementId: 'G-0HR3R44BY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuKJSwtrACpncxgzwPxt-NZGeQ6ujCT38',
    appId: '1:1092996801737:android:1d96646540d6f16c64d918',
    messagingSenderId: '1092996801737',
    projectId: 'jahotel-c3b37',
    storageBucket: 'jahotel-c3b37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvkjJ-i66RJfKtrr64G_0sEh5Sbpig-fw',
    appId: '1:1092996801737:ios:01a37a94375f770764d918',
    messagingSenderId: '1092996801737',
    projectId: 'jahotel-c3b37',
    storageBucket: 'jahotel-c3b37.appspot.com',
    androidClientId:
        '1092996801737-0q7fjlmccvr6r9e38piuq68olnd3rhm7.apps.googleusercontent.com',
    iosClientId:
        '1092996801737-6shmvkqfq3en3ul0pc65khg0hpem86b3.apps.googleusercontent.com',
    iosBundleId: 'com.ninejahotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvkjJ-i66RJfKtrr64G_0sEh5Sbpig-fw',
    appId: '1:1092996801737:ios:01a37a94375f770764d918',
    messagingSenderId: '1092996801737',
    projectId: 'jahotel-c3b37',
    storageBucket: 'jahotel-c3b37.appspot.com',
    androidClientId:
        '1092996801737-0q7fjlmccvr6r9e38piuq68olnd3rhm7.apps.googleusercontent.com',
    iosClientId:
        '1092996801737-6shmvkqfq3en3ul0pc65khg0hpem86b3.apps.googleusercontent.com',
    iosBundleId: 'com.ninejahotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkEUhURDJzrBwUkAa41GXy928XXXiY23A',
    appId: '1:1092996801737:web:9838037c14a27f1a64d918',
    messagingSenderId: '1092996801737',
    projectId: 'jahotel-c3b37',
    authDomain: 'jahotel-c3b37.firebaseapp.com',
    storageBucket: 'jahotel-c3b37.appspot.com',
    measurementId: 'G-N2ZWBGQGRP',
  );
}
